flathub/io.github.zen_browser.zen

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.13. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.13

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.15. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.15

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.18. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.18

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.19. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.19

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.20. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.20

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.21. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.21

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.22. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.22

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.23. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.23

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.24. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.24

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.26. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.26

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.27. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.27

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.28. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.28

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.29. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.29

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.30. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.30

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.32. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.32

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.33. 
@mauro-balades
=> 🚀 Update to version 1.0.0-a.33

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.37. 
=> 🚀 Update to version 1.0.0-a.37

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.0-a.39. 
=> 🚀 Update to version 1.0.0-a.39

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.
=> 🚀 Update to version 1.0.1-a

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.1.
=> 🚀 Update to version 1.0.1-a.1

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.2.
=> 🚀 Update to version 1.0.1-a.2

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.3.
=> 🚀 Update to version 1.0.1-a.3

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.4.
=> 🚀 Update to version 1.0.1-a.4

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.5.
=> 🚀 Update to version 1.0.1-a.5

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.6.
=> 🚀 Update to version 1.0.1-a.6

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.7.
=> 🚀 Update to version 1.0.1-a.7

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.8.
=> 🚀 Update to version 1.0.1-a.8

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.9.
=> 🚀 Update to version 1.0.1-a.9

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.11.
=> 🚀 Update to version 1.0.1-a.11

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.12.
=> 🚀 Update to version 1.0.1-a.12

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.13.
=> 🚀 Update to version 1.0.1-a.13

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.14.
=> 🚀 Update to version 1.0.1-a.14

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.15.
=> 🚀 Update to version 1.0.1-a.15

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.18.
=> 🚀 Update to version 1.0.1-a.18

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.1-a.19.
=> 🚀 Update to version 1.0.1-a.19

io.github.zen_browser.zen.yml
This PR updates the Zen Browser Flatpak package to version 1.0.2-b.5.
@mr-cheff please review and merge this PR.
=> 🚀 Update to version 1.0.2-b.5
